import SwiftUI

struct PrivacyPolicyView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                Group {
                    Text("Privacy Policy")
                        .font(.title)
                        .fontWeight(.bold)

                    Text("Last updated: February 21, 2026")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Text("Scam Llama is committed to protecting your privacy. This policy explains what data we collect, how it's used, who it's shared with, and your rights.")
                }

                policySection(
                    title: "1. Data We Collect",
                    content: """
                    Scam Llama processes the following data locally on your device:

                    \u{2022} Conversation text you paste or scan via screenshots
                    \u{2022} Photos you select for AI-generated image detection
                    \u{2022} Red flag checklist selections
                    \u{2022} Analysis history and results

                    All data is stored on-device using encrypted storage (iOS Data Protection). Scam Llama does not collect, store, or transmit data to any server we operate.
                    """
                )

                policySection(
                    title: "2. How We Collect Data",
                    content: """
                    Data is collected only through your direct actions within the app:

                    \u{2022} Text input: You manually paste or type conversation text, or select a screenshot for OCR text extraction (performed on-device using Apple's Vision framework)
                    \u{2022} Photo selection: You manually select a photo from your photo library using Apple's PhotosPicker
                    \u{2022} Checklist input: You manually toggle checklist items

                    No data is collected automatically, in the background, or without your direct initiation.
                    """
                )

                policySection(
                    title: "3. Third-Party AI Services — Data Sharing",
                    content: """
                    Scam Llama optionally integrates with two third-party AI services. Data is only shared with these services when (a) you have added an API key for that service, and (b) you have given explicit in-app permission to share data with that specific service. You are prompted for permission before any data leaves your device.

                    Chat Analysis — Anthropic (Claude API)
                    \u{2022} What is sent: The conversation text you entered or extracted from a screenshot. No personal identifiers, contact names, platform names, or device information are included.
                    \u{2022} Where it is sent: Anthropic's Claude Messages API at api.anthropic.com
                    \u{2022} Who receives it: Anthropic, PBC (San Francisco, CA)
                    \u{2022} Why: To analyze conversation text for scam and fraud patterns using AI
                    \u{2022} Their policy: https://www.anthropic.com/policies/privacy
                    \u{2022} Without an API key: Analysis is performed entirely on-device using local pattern matching. No data is sent anywhere.

                    Photo Verification — Reality Defender
                    \u{2022} What is sent: The photo image you selected. Image EXIF metadata is stripped. No file names, personal information, or device information are included.
                    \u{2022} Where it is sent: Reality Defender's API at api.prd.realitydefender.xyz
                    \u{2022} Who receives it: Reality Defender, Inc. (New York, NY)
                    \u{2022} Why: To detect whether a profile photo was generated by AI
                    \u{2022} Their policy: https://www.realitydefender.com/privacy-policy
                    \u{2022} Without an API key: Analysis is performed entirely on-device using Apple's Vision framework and image heuristics. No data is sent anywhere.

                    Both third-party services process data according to their own privacy policies. Anthropic and Reality Defender both provide protections for user data, including not using API data to train their models.
                    """
                )

                policySection(
                    title: "4. User Consent & Permissions",
                    content: """
                    Scam Llama requires your explicit permission before sharing data:

                    \u{2022} On first launch, a consent screen explains all third-party data sharing
                    \u{2022} Before the first time data is sent to each third-party service, a specific alert explains exactly what data will be sent and to whom
                    \u{2022} You can choose "Analyze Locally Only" at any prompt to keep all data on-device
                    \u{2022} You can revoke all data processing consent at any time in Settings
                    \u{2022} Revoking consent immediately stops all third-party data sharing

                    All features work without any API keys using on-device analysis only.
                    """
                )

                policySection(
                    title: "5. API Keys",
                    content: """
                    Your API keys for Anthropic and Reality Defender are stored securely in the iOS Keychain with hardware-level encryption. Keys are only used to authenticate requests to their respective services and are never sent to our servers or shared with any other party.
                    """
                )

                policySection(
                    title: "6. Data Storage & Security",
                    content: """
                    \u{2022} All analysis history is stored locally on your device only
                    \u{2022} Data is encrypted at rest using NSFileProtectionComplete
                    \u{2022} No data is backed up to our servers (no servers exist)
                    \u{2022} You can delete all data at any time from Settings
                    \u{2022} Photos stored in history are saved as compressed JPEG data on-device only
                    """
                )

                policySection(
                    title: "7. No Tracking or Analytics",
                    content: """
                    Scam Llama does not:
                    \u{2022} Track your activity or behavior
                    \u{2022} Collect analytics, crash reports, or usage data
                    \u{2022} Use advertising identifiers (IDFA)
                    \u{2022} Share data with advertisers or data brokers
                    \u{2022} Use cookies, tracking pixels, or fingerprinting
                    \u{2022} Contain any third-party analytics SDKs
                    """
                )

                policySection(
                    title: "8. Your Rights",
                    content: """
                    You have full control over your data:
                    \u{2022} Delete all stored data from Settings at any time
                    \u{2022} Remove API keys at any time to stop all third-party sharing
                    \u{2022} Revoke data processing consent at any time
                    \u{2022} Uninstall the app to remove all local data
                    \u{2022} Use all features in local-only mode without sharing any data
                    """
                )

                policySection(
                    title: "9. Children's Privacy",
                    content: """
                    Scam Llama is not intended for children under 13. We do not knowingly collect data from children.
                    """
                )

                policySection(
                    title: "10. Changes to This Policy",
                    content: """
                    If we update this privacy policy, we will update the "Last updated" date above. Continued use of the app after changes constitutes acceptance of the revised policy.
                    """
                )

                policySection(
                    title: "11. Contact",
                    content: """
                    For questions about this privacy policy or your data, contact us at:
                    scamllama.app@gmail.com
                    """
                )
            }
            .padding()
        }
        .brandedNavigationBar(title: "Privacy Policy", icon: "hand.raised.fill")
    }

    private func policySection(title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
            Text(content)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
    }
}

#Preview {
    NavigationStack {
        PrivacyPolicyView()
    }
}
