import SwiftUI
import SwiftData
import PhotosUI

struct PhotoVerificationView: View {
    @Environment(\.modelContext) private var modelContext
    @State private var viewModel = PhotoVerificationViewModel()
    @State private var selectedItem: PhotosPickerItem?
    @State private var showAPIConsentAlert = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 24) {
                    // Info card
                    VStack(alignment: .leading, spacing: 8) {
                        Label("AI Photo Detection", systemImage: "sparkles")
                            .font(.subheadline)
                            .fontWeight(.semibold)
                            .foregroundStyle(.purple)

                        Text("Upload a profile photo to check if it was generated by AI. Combines on-device analysis with Reality Defender's deepfake detection.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
                    .background(Color.purple.opacity(0.08))
                    .clipShape(RoundedRectangle(cornerRadius: 12))
                    .padding(.horizontal)

                    // Image preview
                    if let image = viewModel.selectedImage {
                        Image(uiImage: image)
                            .resizable()
                            .scaledToFit()
                            .frame(maxHeight: 300)
                            .clipShape(RoundedRectangle(cornerRadius: 16))
                            .shadow(color: .black.opacity(0.1), radius: 10, y: 5)
                            .padding(.horizontal)
                    }

                    // Loading state
                    if let message = viewModel.stateMessage {
                        HStack(spacing: 12) {
                            ProgressView()
                            Text(message)
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                        }
                        .padding()
                        .frame(maxWidth: .infinity)
                        .background(Color(.secondarySystemBackground))
                        .clipShape(RoundedRectangle(cornerRadius: 12))
                        .padding(.horizontal)
                    }

                    // Error
                    if let error = viewModel.errorMessage {
                        Label(error, systemImage: "exclamationmark.triangle")
                            .font(.caption)
                            .foregroundStyle(.red)
                            .padding(.horizontal)
                    }

                    // Photo picker
                    PhotosPicker(
                        selection: $selectedItem,
                        matching: .images
                    ) {
                        Label(
                            viewModel.selectedImage == nil ? "Select Profile Photo" : "Choose Different Photo",
                            systemImage: "person.crop.circle.badge.plus"
                        )
                        .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.bordered)
                    .padding(.horizontal)

                    // Analyze button
                    if viewModel.selectedImage != nil {
                        Button {
                            handleAnalyzeTapped()
                        } label: {
                            HStack {
                                if viewModel.isLoading {
                                    ProgressView()
                                        .tint(.white)
                                }
                                Text(viewModel.isLoading ? "Analyzing..." : "Check for AI Generation")
                                    .fontWeight(.semibold)
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 4)
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(.purple)
                        .disabled(viewModel.isLoading)
                        .padding(.horizontal)
                    }

                    // Info label
                    if viewModel.detector.state == .idle {
                        Label("On-device + Reality Defender dual analysis", systemImage: "sparkles")
                            .font(.caption2)
                            .foregroundStyle(.tertiary)
                            .padding(.horizontal)
                    }
                }
                .padding(.vertical)
            }
            .brandedNavigationBar(title: "Check Photo", icon: "person.crop.circle.badge.questionmark")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Clear") { viewModel.reset() }
                        .disabled(viewModel.selectedImage == nil && !viewModel.isLoading)
                }
            }
            .navigationDestination(isPresented: $viewModel.showingResult) {
                if let result = viewModel.analysisResult {
                    PhotoResultView(
                        analysis: result,
                        image: viewModel.selectedImage,
                        onSave: {
                            viewModel.saveResult(modelContext: modelContext)
                        }
                    )
                }
            }
            .onChange(of: selectedItem) { _, newItem in
                guard let newItem else { return }
                Task {
                    if let data = try? await newItem.loadTransferable(type: Data.self),
                       let image = UIImage(data: data) {
                        viewModel.selectedImage = image
                    }
                }
            }
            .alert("Share Photo with Reality Defender?", isPresented: $showAPIConsentAlert) {
                Button("Allow & Analyze") {
                    ConsentManager.shared.acceptPhotoAPIConsent()
                    Task { await viewModel.analyze() }
                }
                Button("Analyze On-Device Only") {
                    Task { await viewModel.analyze() }
                }
                Button("Cancel", role: .cancel) { }
            } message: {
                Text("To provide enhanced AI detection, your selected photo will be uploaded to Reality Defender's API (api.prd.realitydefender.xyz) for deepfake analysis.\n\nData sent: The photo image only. No file names, metadata, or personal information are included.\n\nRecipient: Reality Defender, Inc. — processed under their privacy policy.\n\nYou can also analyze on-device only without uploading the photo.")
            }
        }
    }

    // MARK: - Analyze Flow

    private func handleAnalyzeTapped() {
        // Always have an RD key (embedded), just need photo API consent
        if ConsentManager.shared.hasConsented && !ConsentManager.shared.hasConsentedPhotoAPI {
            showAPIConsentAlert = true
        } else {
            Task { await viewModel.analyze() }
        }
    }
}

#Preview {
    PhotoVerificationView()
        .modelContainer(for: [PhotoCheck.self], inMemory: true)
}
